### ISSUE TITLE
Problemi nell'organizzare le classi RequestDto, ResponseDto e Contatto.

### ISSUE THREAD

**Issue by Giulia2Gargano** [luca-lezzerini/rubrica-ill#4]
Dando un'occhiata alle Issues da lei inviateci, ci sono sorti ancora più dubbi sulla struttura dei corpi delle tre classi sopracitate.
Nella classe RequestDto sappiamo che bisogna inserire una proprietà contatto di tipo contatto, nella classe contatto tutte le proprietà da inserire nell'array, ma abbiamo grandi dubbi su come gestire il ResponseDto. @luca-lezzerini

**Comment by luca-lezzerini** [comment]
La risposta di praticamente tutti i metodi della rubrica è List<Contatto>. Quindi create un DTO con una proprietà di tale tipo

**Comment by luca-lezzerini** [comment]
Intendo List<Contatto>

**Comment by luca-lezzerini** [comment]
Intendo List<Contatto> purtroppo il sistema mi mangia le triangolari. Quindi List parentesi triangolare Contatto parentesi triangolare

**Comment by Giulia2Gargano** [comment]
Dovremmo aver risolto, grazie!
